version: "3.8"

services:
  scheduler:
    build:
      context: .
      dockerfile: docker/scheduler/Dockerfile
    image: library-data-scheduler
    environment:
      - LIBRARY_DATA_DIR=/app/data
      - SCHEDULE_NIGHTLY=0 2 * * *
      # Optional: LT_TOKEN, UA, ENRICH_LIMIT, ENRICH_SLEEP, SINCE, COLLECTIONS, TAGS, SEARCH, REBUILD_FTS
      - LT_TOKEN=${LT_TOKEN:-}
      - UA=${UA:-library-data/levels (+mailto:you@example.com)}
    volumes:
      - ./data:/app/data
    restart: unless-stopped
